name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if needed

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller flet

      - name: Build executable
        run: pyinstaller --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/main.exe
